theme = "jellybeans"

[editor]
scrolloff = 10
line-number = "relative"
cursorline = true
rulers = [121]
# bufferline = "always"
# end-of-line-diagnostics = "hint"
color-modes = true
popup-border = "all"
indent-heuristic = "simple"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "â”‚"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"

[keys.insert]
"C-," = "move_char_left"
"C-." = "move_char_right"

